apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders.fullname" . }}-db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portdb }}
      targetPort: {{ .Values.service.portdb }}
      protocol: TCP
  selector:
    {{- include "ordersdb.selectorLabels" . | nindent 4 }}
