apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.name" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portmq1 }}
      targetPort: {{ .Values.service.portmq1 }}
      protocol: TCP
      name: amp
    - port: {{ .Values.service.portmq2 }}
      targetPort: {{ .Values.service.portmq2 }}
      protocol: TCP
      name: rabbit
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
