apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ui.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ui.serviceAccountName" . }}      
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: SERVER_TOMCAT_ACCESSLOG_ENABLED
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: JAVA_OPTS
            - name: ENDPOINTS_CATALOG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: ENDPOINTS_CATALOG
            - name: ENDPOINTS_CARTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: ENDPOINTS_CARTS
            - name: ENDPOINTS_ORDERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: ENDPOINTS_ORDERS
            - name: ENDPOINTS_CHECKOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: ENDPOINTS_CHECKOUT
            - name: ENDPOINTS_ASSETS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: ENDPOINTS_ASSETS
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}